# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
      tags.datadoghq.com/env: "ctf"
      tags.datadoghq.com/service: "adservice"
      tags.datadoghq.com/version: "0.5.0"
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
        tags.datadoghq.com/env: "ctf"
        tags.datadoghq.com/service: "adservice"
        tags.datadoghq.com/version: "0.5.0"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: "latest"
        ad.datadoghq.com/server.checks: |
          {
            "jmx": {
              "init_config": {
                "is_jmx": true,
                "collect_default_metrics": true,
                "collect_default_jvm_metrics": true,
                "new_gc_metrics": true,
                "conf": [{
                  "include": {
                    "domain": "java.lang",
                    "type": "MemoryPool",
                    "attribute": {
                      "Usage.used": {
                        "metric_type": "gauge",
                        "alias": "jvm.memory_usage"
                        },
                      "Usage.committed": {
                        "metric_type": "gauge",
                        "alias": "jvm.memory_committed"
                        }
                      }
                    }
                }, {
                  "include": {
                  "domain": "java.lang",
                  "type": "Threading",
                  "attribute": {
                    "ThreadCount": {
                     "metric_type": "gauge",
                     "alias": "jvm.threads.active"
                      },
                    "TotalStartedThreadCount": {
                     "metric_type": "gauge",
                      "alias": "jvm.threads.total"
                      }
              }
            }
          }]
              },
              "instances": [{
                "host": "%%host%%",
                "port": "8081",
                "tags": ["pod_name:%%kube_pod_name%%"]
              }]
            }
          }
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
          privileged: false
        #   readOnlyRootFilesystem: true
        image: adservice
        ports:
        - containerPort: 9555
        - name: jmx-metrics
          containerPort: 8081
        env:
        - name: PORT
          value: "9555"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        #- name: DD_TRACE_SAMPLE_RATE
        #  value: "1"
        - name: DD_INVENTORIES_CONFIGURATION_ENABLED
          value: "true"
        - name: DD_PROFILING_DIRECTALLOCATION_ENABLED
          value: "true"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #- name: DD_TRACE_SAMPLING_RULES
        #  value: '[{"service": "*", "sample_rate": 0.2}]'
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: JAVA_OPTS
          value: >-
              -Dcom.sun.management.jmxremote
              -Dcom.sun.management.jmxremote.authenticate=false
              -Dcom.sun.management.jmxremote.ssl=false
              -Dcom.sun.management.jmxremote.local.only=false
              -Dcom.sun.management.jmxremote.port=8081
              -Dcom.sun.management.jmxremote.rmi.port=8081
              -Djava.rmi.server.hostname=$(POD_IP)
              -Ddd.profiling.directallocation.enabled=true

        #- name: DD_ENTITY_ID
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: metadata.uid
        #- name: DD_AGENT_HOST
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: status.hostIP
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        #volumeMounts:
        #  - name: jmx-config-map
        #    mountPath: /etc/datadog-agent/conf.d/jmx.d
      #volumes:
      #  - name: jmx-config-map
      #    configMap:
      #      name: jmx-config-map
      #      items:
      #        - key: jmx-config
      #          path: conf.yaml
        # readinessProbe:
        #   initialDelaySeconds: 40
        #   periodSeconds: 15
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:9555"]
        # livenessProbe:
        #   initialDelaySeconds: 40
        #   periodSeconds: 15
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
